
language: php

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.1

before_script:
  - composer install --prefer-dist --dev

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
